# Generated by Django 3.1.5 on 2021-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='data',
            name='fill',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='data',
            name='icon',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
