# Generated by Django 3.1.5 on 2021-04-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210409_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='d',
        ),
    ]
