# Generated by Django 3.1.5 on 2021-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='utxt',
            new_name='uemail',
        ),
        migrations.AddField(
            model_name='manager',
            name='uuser',
            field=models.TextField(default='-'),
        ),
    ]
