# Generated by Django 3.1.5 on 2021-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210413_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.AlterField(
            model_name='manager',
            name='uuser',
            field=models.TextField(),
        ),
    ]
